import { type NextPage } from "next";
import Head from "next/head";
import Loading from "../components/loading"
import Paragraph from "../components/paragraph"
import { useState, useContext } from 'react';
import { AppContext } from "./_app";


const Home: NextPage = () => {
  const {storys, setStorys} = useContext(AppContext);
  const {index} = useContext(AppContext);

  console.log(`===== index ${index}`);

  const [buttonVisible, setButtonVisible] = useState(true);
  
  return (
    <>
      <Head>
        <title>Bed-Time Story</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
      </Head>
      <main className="flex h-screen flex-col items-center justify-center bg-black text-gray-300">
        <div className="text-3xl sm:text-5xl px-4 py-4 max-w-3xl  h-max">
          {Paragraph()}
        </div>
        <div className="text-5xl px-4 py-4" style={{ display: buttonVisible ? "visible" : "hidden" }}>
        {Loading()}
        </div>
      </main>
    </>
  );
};

export default Home;
